### ISSUE TITLE
Broadcast events

### ISSUE THREAD

**Issue by Fabiomad85** [mimiz/rabbitmq-event-manager#11]
How can I share the same event over multiple services like broadcast?

Because I need multiple consumer that do something when an event has been emitted from another service, 

HOw can I do that?

Thanks

**Comment by mimiz** [comment]
Hi, 

Sorry, for the late response, but I was not available before.
Actually you can "listen" one event from many clients, but you may have to define a client name while creating the connection to RabbitMQ.

The Basic example of the README explains this.

Regards
