### ISSUE TITLE
messages flushing afer handling 10 messages

### ISSUE THREAD

**Issue by shaunie2fly** [mimiz/rabbitmq-event-manager#7]
After receiving 10 requests and ack correctly i get the following.

2019-06-09T06:36:43.851Z [PRODUCER] info: Message published to exchange PRODUCER.EVENT
2019-06-09T06:36:44.041Z [PRODUCER] warn: Message has been flushed, after 10 times requeued.

**Comment by mimiz** [comment]
Yes I will fix it asap ! Sorry for that

**Comment by mimiz** [comment]
Hi, I've just published the version 1.0.11 to npm, with a fix for this issue, I hope it will work fine for you.

Please feel free to give any ideas to improve the lib ...

**Comment by shaunie2fly** [comment]
Thanks very much :) I definitely will let you know if I think of something.
